# Generated by Django 6.0.2 on 2026-02-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_photo_blouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blouse',
            name='blouse_name',
        ),
        migrations.AddField(
            model_name='blouse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blouse_images/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='customer_photos/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
